name: Deploy to Vercel Preview

on:
  push:
    branches-ignore:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout-vercel
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node-vercel
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install-deps-vercel
        run: npm ci

      - name: Build project
        id: build-vercel
        run: npm run build

      - name: Install Vercel CLI
        id: install-vercel-cli
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        id: pull-vercel-env
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        id: build-vercel-artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy-vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
